### PR TITLE
added variation for spanish

### PR DESCRIPTION
**Pull request by ngeorger**

### CODE REVIEW

**Comment by onweru** [comment]
Thanks for contributing @ngeorger, I will make a few changes on top of your changes and merge.

**Comment by ngeorger** [comment]
> Thanks for contributing @ngeorger, I will make a few changes on top of your changes and merge.

No, thank you! I'm available if you pretend to fully translate the template, nice job, thank yyou very much.

**Review by onweru — COMMENTED** [review]
Just a heads up, changes that have nothing to do with translation will be dropped i.e changes in `favicon.html`, `header.html` & `mode.html` templates.

**Comment by ngeorger** [comment]
> 

Yes, my mistake, that commit wast supposed to be pushed here, my bad.

**Comment by onweru** [comment]
@ngeorger,

> I'm available if you pretend to fully translate the template

If you like,  I have added more [translations](https://github.com/onweru/newsroom/blob/master/i18n/es.toml), if you like you can open a new PR with the translations updated.

In addition to those changes, I made 1/ logo & 2/ favicons directory configurable via the [config.toml file](https://github.com/onweru/newsroom/blob/fdc97fb8da602e0c8192ff4e57a794618865d072/exampleSite/config.toml#L35-L36). This way, you don't have to make the edits you made in bd8643d10f62dc2920e89e616ac95eb1e4cf9630.

**Pull request merged**
